name: knutsen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21401
title: 'SELECT * FROM x LEFT JOIN life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#a9b4a3'
    - '#fefefe'
    - '#655e27'
    - '#f2fc08'
  brandStrength: 0.43707325402647257
  lightness: 0.6373172616586089
  saturation: 0.8888289611786604
  rhythmicContrast: 0.6803982600104064
purpose: []
